# GpuBuffer
input_stream: "input_video"

# CaratFaceEffectList
input_stream: "carat_face_effect_list"

# int
input_side_packet: "num_faces"

# GpuBuffer
output_stream: "output_video"

# std::vector<NormalizedLandmarkList>
output_stream: "multi_face_landmarks"

# std::vector<face_geometry::FaceGeometry>
output_stream: "multi_face_geometry"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 63.0  # 63 degrees
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "SIZE:image_size"
}

node {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "NUM_FACES:num_faces"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "DETECTIONS:face_detections"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}

node {
  calculator: "FaceGeometryFromLandmarks"
  input_stream: "MULTI_FACE_LANDMARKS:multi_face_landmarks"
  input_stream: "IMAGE_SIZE:image_size"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
}

node {
  calculator: "CaratFaceEffectRendererCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
  input_stream: "CARAT_FACE_EFFECT_LIST:carat_face_effect_list"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "IMAGE_GPU:face_effect_output_video"
}

node {
  calculator: "RectToRenderDataCalculator"
  input_stream: "NORM_RECTS:face_rects_from_landmarks"
  output_stream: "RENDER_DATA:rects_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.RectToRenderDataCalculatorOptions] {
      filled: false
      color { r: 255 g: 0 b: 0 }
      thickness: 4.0
    }
  }
}

node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:face_effect_output_video"
  input_stream: "rects_render_data"
  output_stream: "IMAGE_GPU:output_video"
}
