# MediaPipe face mesh rendering subgraph.

type: "CaratFaceRendererGpu"

# GPU image. (GpuBuffer)
input_stream: "IMAGE:input_image"
# Collection of detected/predicted faces, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
input_stream: "LANDMARKS:multi_face_landmarks"

input_side_packet: "FOREHEAD_SIZE:forehead_size"
input_side_packet: "CHEEKBONE_SIZE:cheekbone_size"
input_side_packet: "TEMPLE_SIZE:temple_size"
input_side_packet: "CHIN_SIZE:chin_size"
input_side_packet: "CHIN_HEIGHT:chin_height"
input_side_packet: "CHIN_SHARPNESS:chin_sharpness"
input_side_packet: "EYE_SIZE:eye_size"
input_side_packet: "EYE_HEIGHT:eye_height"
input_side_packet: "EYE_SPACING:eye_spacing"
input_side_packet: "FRONT_EYE_SIZE:front_eye_size"
input_side_packet: "UNDER_EYE_SIZE:under_eye_size"
input_side_packet: "PUPIL_SIZE:pupil_size"
input_side_packet: "NOSE_HEIGHT:nose_height"
input_side_packet: "NOSE_WIDTH:nose_width"
input_side_packet: "NOSE_BRIDGE_SIZE:nose_bridge_size"
input_side_packet: "NOSE_BASE_SIZE:nose_base_size"
input_side_packet: "NOSE_END_SIZE:nose_end_size"
input_side_packet: "PHILTRUM_HEIGHT:philtrum_height"
input_side_packet: "LIP_SIZE:lip_size"
input_side_packet: "LIP_END_UP:lip_end_up"

# GPU image with rendered data. (GpuBuffer)
output_stream: "IMAGE:output_image"

node {
  calculator: "CaratFaceRenderCalculator"
  input_stream: "IMAGE_GPU:input_image"
  input_stream: "MULTI_FACE_LANDMARKS:multi_face_landmarks"
  input_side_packet: "FOREHEAD_SIZE:forehead_size"
  input_side_packet: "CHEEKBONE_SIZE:cheekbone_size"
  input_side_packet: "TEMPLE_SIZE:temple_size"
  input_side_packet: "CHIN_SIZE:chin_size"
  input_side_packet: "CHIN_HEIGHT:chin_height"
  input_side_packet: "CHIN_SHARPNESS:chin_sharpness"
  input_side_packet: "EYE_SIZE:eye_size"
  input_side_packet: "EYE_HEIGHT:eye_height"
  input_side_packet: "EYE_SPACING:eye_spacing"
  input_side_packet: "FRONT_EYE_SIZE:front_eye_size"
  input_side_packet: "UNDER_EYE_SIZE:under_eye_size"
  input_side_packet: "PUPIL_SIZE:pupil_size"
  input_side_packet: "NOSE_HEIGHT:nose_height"
  input_side_packet: "NOSE_WIDTH:nose_width"
  input_side_packet: "NOSE_BRIDGE_SIZE:nose_bridge_size"
  input_side_packet: "NOSE_BASE_SIZE:nose_base_size"
  input_side_packet: "NOSE_END_SIZE:nose_end_size"
  input_side_packet: "PHILTRUM_HEIGHT:philtrum_height"
  input_side_packet: "LIP_SIZE:lip_size"
  input_side_packet: "LIP_END_UP:lip_end_up"
  output_stream: "IMAGE_GPU:output_image"
}
